server:
  port: 8092
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: service-channel
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.31.161:3306/ft_sql?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  mybatis:
  mapper-locations: classpath*:/mapper/*.xml